export const statOrder = [
  "Type",
  "Biome",
  "Blunt",
  "Pierce",
  "Slash",
  "Total Damage",
  "Durability",
  "Backstab",
  "Stagger",
  "Knockback",
  "Stamina",
  "Block Armor",
  "Block Force",
  "Parry Bonus",
  "Movement",
  "Weight",
  "Notes",
];

export const comparisonAlgorithms = {
  Type: "text",
  Biome: "text",
  Blunt: "biggerIsBetter",
  Pierce: "biggerIsBetter",
  Slash: "biggerIsBetter",
  TotalDamage: "biggerIsBetter",
  Durability: "biggerIsBetter",
  Backstab: "biggerIsBetter",
  Stagger: "biggerIsBetter",
  Knockback: "biggerIsBetter",
  Stamina: "lowerIsBetter",
  Movement: "percentBiggerIsBetter",
  "Block Armor": "biggerIsBetter",
  "Block Force": "biggerIsBetter",
  "Parry Bonus": "biggerIsBetter",
  Weight: "lowerIsBetter",
  Notes: "text",
};
